version: '3.8'

services:
  app:
      build: .
      container_name: "spring_app_countries_render"
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://viaduct.proxy.rlwy.net:15286/railway
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: zlYTQXDrERWPGvKrioUzxZnZEOOHLqJr
      restart: always

  
